config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
  end

  resources :users, only: [:show, :update]do
    resources :bookings, only: [ :index ]
  end

  resources :tools do
    resources :bookings, only: [ :new, :create, :show, :edit ] do
      resources :reviews, only: [ :new, :create ]
    end
    resources :reviews, only: [ :show, :index ]
  end





  # get '/profile', to: 'pages#profile'

  root to: 'pages#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tool.rb
class Tool < ApplicationRecord
  CATEGORIES = ["hand tools", "power tools", "painting", "home decor", "yard work", "entertainment", "cooking", "camping"]
  belongs_to :user
  has_many :reviews, through: :booking
  has_many :bookings, dependent: :destroy
  validates :tags, presence: true
  validates :title, presence: true
  validates :price, presence: true
  validates :available, presence: true
  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_tool, only: [ :show, :edit, :update, :destroy ]
  before_action :set_user, only: [ :new, :create, :index ]

  def new
    @tool = Tool.new
  end

  def edit
  end

  def show
    @tool = Tool.find(params[:id])
    @user = User.find(@tool[:user_id])
    @bookings = @tool.bookings
    @reviews = []

    @hash = Gmaps4rails.build_markers(@tool) do |tool, marker|
        marker.lat tool.user.latitude if !tool.user.latitude.nil?
        marker.lng tool.user.longitude if !tool.user.longitude.nil?
    end
  end

  def index
    if !params[:title].nil?
      @tools = search_title
    else
      @tools = search_category
    end

    @hash = Gmaps4rails.build_markers(@tools) do |tool, marker|
        marker.lat tool.user.latitude if !tool.user.latitude.nil?
        marker.lng tool.user.longitude if !tool.user.longitude.nil?
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def search_title
     @tools = if params[:title]
      Tool.where('title iLIKE ?', "%#{params[:title]}%")
    else
      Tool.all
    end
  end

  def search_category
    if params[:category]
      filtered = []
      Tool.all.each do |tool|
        filtered << tool if tool.tags.include? params[:category]
      end
      @tools = filtered
    else
      @tools = Tool.all
    end
  end


  def update
    @tool.update(tool_params)
    redirect_to tools_path
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.tags = params[:tool][:tags].reject { |c| c.empty? }
    @tool.user = @user
    @tool.available = true
    if @tool.save!
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def destroy
    @tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:user_id, :tags, :description, :title, :price, :available, :photo, :photo_cache)
  end

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def set_user
    @user = User.find(current_user[:id])
  end
end

app/views/tools/edit.html.erb
<div class="wrapper-tool-add">
  <div class="container">
    <div class="new-tool-box">
  <%= simple_form_for @tool do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :tags, as: :check_boxes, collection: Tool::CATEGORIES, name: nil %>
    <%= f.input :price %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
      <div class="text-center">
        <%= f.submit "Edit" %>
  <% end %>
  <br>
  <br>
  <%= link_to 'Back', :back %>
      </div>
    </div>
  </div>
</div>

app/views/tools/index.html.erb
<div id="searchbar-wrapper">
  <div id="searchbar">
    <%= render 'shared/searchbar'  %>
  </div>
</div>


<!-- <div id="map" style="width: 100%; height: 250px;"></div> -->

<!--
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>
-->
<div class="container tool-index-header">
  <p><%= pluralize @tools.count, "result" %> for <%= params[:title] %></p>
</div>
<div class="container">
  <div class="row">
    <% @tools.each do |tool| %>
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <% image_url = tool.photo || 'http://placehold.it/50x300' %>
        <div class="card-tool-index card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_url %>');">
          <div class="card-price-show-tools card-price-show">
            <h3>$<%= tool.price %>/day</h3>
          </div>
          <div class="card-description">
            <h2><%= tool.title %></h2>
          </div>
          <%= link_to "", tool_path(tool), {class: "card-link"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tools/new.html.erb
<div class="wrapper-tool-add">
  <div class="container">
    <div class="new-tool-box">
        <%= simple_form_for @tool do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :tags, as: :check_boxes, collection: Tool::CATEGORIES%>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
      <div class="text-center">
          <%= f.submit "Create Listing", class: "create-listing-button search-button navbar-wagon-item navbar-wagon-button btn" %>
        <% end %>
        <br>
        <br>
        <%= link_to 'Back', :back %>
      </div>
    </div>
  </div>

app/views/tools/show.html.erb
<div class="wrapper-tools-show">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <%= render 'shared/card' %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="card-show text-center card-description-show">
          <% if @user != current_user %>
            <%= link_to user_path(current_user) do %>
              <% avatar_url = @user.facebook_picture_url || @user.photo %>
              <%= image_tag avatar_url, class: "avatar-medium" %>

            <% end %>
            <h2 class="before"><%= @user.first_name %>'s <%= @tool.title %></h2>
            <p class="before">"<%= @tool.description %>"</p>
            <hr>
            <%= link_to "Request to Rent", new_tool_booking_path(@tool), class: "tools-show-buttons search-button navbar-wagon-item navbar-wagon-button btn before edit" %>


          <% else %>
            <%= link_to "Edit", edit_tool_path(@tool), {class: "tools-show-buttons search-button navbar-wagon-item navbar-wagon-button btn edit"}%>
            <p><%= link_to "Remove", tool_path(@tool), method: :delete, class: "tools-show-buttons search-button navbar-wagon-item navbar-wagon-button btn before edit destroy" %></p>
          <% end %>
          <p><%= link_to 'Back', :back, {class: "non-button-link"} %><p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-reviews">
  <div class="container text-center">
    <h1 class="text-center"><strong>Reviews</strong></h1>
    <%= render 'shared/page_break_icon' %>
    <% avatar_url = @user.facebook_picture_url || @user.photo %>
    <ul class="list-reviews">
      <li><p>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
      </p>

    </ul>
    <h4>"I loved using this and it was in great condition"</h4>
  </div>
</div>

<div id="map-tool-show" style="width: 100%; height: 250px"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map-tool-show' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>