config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
  end

  resources :users, only: [:show, :update]do
    resources :bookings, only: [ :index ]
  end

  resources :tools do
    resources :bookings, only: [ :new, :create, :show, :edit ] do
      resources :reviews, only: [ :new, :create ]
    end
    resources :reviews, only: [ :show, :index ]
  end





  # get '/profile', to: 'pages#profile'

  root to: 'pages#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tool
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_booking, only: [ :show, :edit, :update ]
  before_action :set_tool, only: [ :new ]

  def index
    @disable_nav = true
    @bookings = Booking.where(user_id: current_user)
  end

  def show
    @disable_nav = true
    @tool = Tool.find(params[:tool_id])
    @user = User.find(@tool[:user_id])
    @booking.tool = @tool
    @hash = Gmaps4rails.build_markers(@tool) do |tool, marker|
        marker.lat tool.user.latitude if !tool.user.latitude.nil?
        marker.lng tool.user.longitude if !tool.user.longitude.nil?
    end
  end

  def new
    @disable_nav = true
    @booking = Booking.new
  end

  def create
    @disable_nav = true
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new(booking_params)
    @booking.tool = @tool
    @booking.user = current_user
    @booking.save!
    redirect_to user_bookings_path(current_user)
  end

  def edit
    @disable_nav = true
  end

  def update
    @disable_nav = true
    @booking.update(booking_params)
    redirect_to user_bookings_path(current_user)
  end

  private

  def booking_params
    booking_params = params.require(:booking).permit(:start_time, :end_time)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_tool
    @tool = Tool.find(params[:tool_id])
  end
end

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="wrapper-title text-center"><h1>My Bookings</h1></div>
<div class="container">
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-xs-12 col-sm-4 container container-booking">
        <div class="card card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= booking.tool.photo %>');">
          <div class="card-category"><h5><%= booking.tool.title %></h5></div>
            <div class="card-time-booking">
              <h4><%= booking.start_time.strftime('%b%_d') %> - <%= booking.end_time.strftime('%b%_d') %></h4>
            </div>
            <%= link_to "", tool_booking_path(booking.tool, booking), {class: "card-link"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="wrapper-tool-add">
  <div class="container">
    <div class="new-tool-box text-center">
        <h3>You're booking:</h3>
        <h3><%= @tool.title %></h3>
        <div class="input-daterange input-group booking-form">
            <%= simple_form_for [@tool, @booking] do |f| %>
              <%= f.input :start_time, as: :date, :class => 'datepicker' %>
              <%= f.input :end_time, as: :date, :class => 'datepicker' %>
              <%= f.hidden_field :tool_id, value: @tool.id %>
          <div class="text-center">
              <%= f.submit "Confirm Booking", class: "new-booking-button search-button navbar-wagon-item navbar-wagon-button btn" %>
            <% end %>
          </div>
        </div>
        <h3>for $<%= @tool.price %>/day</h3>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(function(){
      $('.datepicker').datepicker();
    });
  <% end %>
<% end %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="wrapper-tools-show">
    <div class="container" id="container-bookings-show">
      <div class="card-show" id="card-bookings-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= @tool.photo %>');">
      </div>
         <div class="card-description-show" id="info-bookings-show">
          <h2>Booking Details</h2><br>
          <p><%= @tool.title %></p>
          <p><%= @booking.start_time.strftime("%b %e") %> - <%= @booking.end_time.strftime("%b %e") %></p>
          <p>$<%= @tool.price %> per day</p><br>
          <%= link_to 'Write Review', new_tool_booking_review_path(@tool, @booking), { class: "search-button navbar-wagon-item navbar-wagon-button btn" } %>
          <br><br>
          <p><%= link_to 'Back', :back, { id: "back-link" } %></p>
        </div>
    </div>
  </div>
</div>
<div id="map-bookings-show" style="width: 66%; height: 250px; margin-left: 280px; border-radius: 3px;"></div>
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map-bookings-show' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>