config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
  end

  resources :users, only: [:show, :update]do
    resources :bookings, only: [ :index ]
  end

  resources :tools do
    resources :bookings, only: [ :new, :create, :show, :edit ] do
      resources :reviews, only: [ :new, :create ]
    end
    resources :reviews, only: [ :show, :index ]
  end





  # get '/profile', to: 'pages#profile'

  root to: 'pages#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content text-center">
    <h1>ShedShare</h1>
    <h2>Need tools for your next project? Rent from your neighbors!</h2>
    <% if user_signed_in? %>
    <% else %>
      <a href="/users/signup"><p>(Sign up and start renting your tools today)</p></a>
    <% end  %>

    <%= render 'shared/searchbar'  %>
  </div>

</div>

app/views/shared/_bookings_display.html.erb
<div class="container">
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-xs-3 col-sm-6 col-md-4 col-lg-3">
        <% image_url = booking.tool.photo || 'http://placehold.it/50x300' %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_url %>');">
          <div class="card-price-show">
            <h3>$<%= booking.tool.price %>/day</h3>
          </div>
          <div class="card-description">
            <h2><%= booking.tool.title %></h2>
          </div>
          <%= link_to "", tool_booking_path(booking.tool, booking), {class: "card-link"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= @tool.photo %>');">
            <div class="card-price-show">
              <h3>$<%= @tool.price %>/day</h3>
            </div>
            <div class="card-stars">
              <ul class="list-reviews">
              <li><p>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
              </p>

            </ul>
            </div>
            <a class="card-link-show" href="" ></a>
        </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container footer-icons">
    <ul class="list-inline footer-list-right">
      <li><a href='#'><p>Terms</p></a></li>
      <li><a href='#'><p>Privacy</p></a></li>
      <li><a href='#'><i class="fa fa-facebook"></i></a></li>
      <li><a href='#'><i class="fa fa-twitter"></i></a></li>
      <li><a href='#'><i class="fa fa-youtube"></i></a></li>
    </ul>
  </span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- should have an IF/ELSE clause telling which navbar to load -->
<% if user_signed_in? %>
  <%= render "shared/navbar_online" %>
<% else %>
  <%= render "shared/navbar_offline" %>
<% end %>

app/views/shared/_navbar_offline.html.erb
<% show_nav = true unless !@disable_nav.nil? %>


<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand navbar-wagon-link"><img src="<%= asset_path( 'logo.svg' ) %>" class="logo-icon"></a>

<% if show_nav != false %>
    <div id="searchbar-wrapper">
    <div id="searchbar">
      <%= render 'shared/searchbar'  %>
    </div>
  </div>
<% end %>






  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Log in Link -->
    <%= link_to "LOG IN", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Button (call-to-action) -->
    <%= link_to "SIGN UP", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "SIGN UP", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "LOG IN", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_online.html.erb
<% show_nav = true unless !@disable_nav.nil? %>

<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand navbar-wagon-link"><img src="<%= asset_path( 'logo.svg' ) %>" class="logo-icon"></a>

<% if !show_nav.nil? && show_nav != false %>
    <div id="searchbar-wrapper">
    <div id="searchbar">
      <%= render 'shared/searchbar'  %>
    </div>
  </div>
<% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Navigation buttons -->
    <%= link_to "CREATE LISTING", new_tool_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Log Out Link -->
    <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar Link to Profile -->
    <%= link_to user_path(current_user) do %>
      <% avatar_url = current_user.facebook_picture_url || current_user.photo %>
      <%= image_tag avatar_url, class: "avatar" %>
    <% end %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Log Out</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Tools</a></li>
        <li><a href="#">Messages</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbaronline.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand navbar-wagon-link">
    <h3>ShedShare <i class="fa fa-handshake-o" aria-hidden="true"></i></h3>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Navigation buttons -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Tools</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Log in Link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Log Out</a>

    <!-- Button (call-to-action) -->
    <img src="http://lorempixel.com/200/200" alt="user" class="avatar">

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Log Out</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Tools</a></li>
        <li><a href="#">Messages</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_page_break_icon.html.erb
<img src="<%= asset_path( 'logo_line_break.svg' ) %>" class="page-break-icon">

app/views/shared/_searchbar.html.erb
<div class="search text-center" id="for_index_page">
  <div class="search-by-tool search-index form-inline">

    <%= form_tag(tools_path, method: :get) do %>
      <%= text_field_tag :title, params[:title], :placeholder => "lawn mower", class: "search-by-tool-input" %>
      <%= submit_tag 'Search', name: nil, class: "search-button navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>

  </div>
</div>

app/views/shared/_tools_display.html.erb
<div class="wrapper" id="wrapper-my-tools">
  <div class="container">
    <div class="row">
      <% @tools.each do |tool| %>
        <div class="col-xs-3 col-sm-6 col-md-4 col-lg-3">
          <% image_url = tool.photo || 'http://placehold.it/50x300' %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_url %>');">
            <div class="card-price-show">
              <h3>$<%= tool.price %>/day</h3>
            </div>
            <div class="card-description">
              <h2><%= tool.title %></h2>
            </div>
            <%= link_to "", tool_path(tool), {class: "card-link"} %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user_form.html.erb
<%= simple_form_for @user,
  :url => user_path(@user.id),
  :html => {class: "form-horizontal"}, method: :put,
  :defaults => { :label_html => { :class => "col-lg-3 control-label" },
  :input_html => { :class => "form-control form-edit"} } do |f| %>

  <h3 class="text-center personal-info-title">Personal info</h3>
    <% if @editable && devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :address  %>
  <%# f.input :photo %>
  <%# f.input :photo_cache, as: :hidden %>
  <% if @editable %>



    <button class="btn btn-primary edit-button-profile " id="profile-edit-button" type="button">Edit</button>
    <%= f.button :submit, "Save", :class => "btn btn-primary save-button-profile", :id => "profile-save-button" %>
    <button class="btn btn-primary cancel-button-profile" id="cancel-edit-button" type="button">Cancel</button>
  <% end %>
<% end %>




<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    <% if @editable %>
          $(document).ready( function() {
          // Toggling whether the form is enabled or disabled.

          // Disabled by Default
          $(".form-edit").prop('disabled', true);
          $("button#cancel-edit-button").hide();
          $("input#profile-save-button").hide();
          $("div#new-photo-upload").hide();
          $("div#hide-password").hide();


          // Enable form when clicking edit
          $("button#profile-edit-button").click(function() {
          $( ".form-edit").prop('disabled', false );
        // Upon clicking edit, hide edit button and show save/cancel
          $( "input#profile-save-button" ).show();
          $( "button#cancel-edit-button" ).show();
          $( "button#profile-edit-button" ).hide();
          $("div#new-photo-upload").show();
          $("div#hide-password").show();
          });

      // Disable form if they cancel
      $("button#cancel-edit-button").click(function() {
      console.log("holla");
      $( ".form-edit").prop('disabled', true);
      $( "input#profile-save-button" ).hide();
      $( "button#cancel-edit-button" ).hide();
      $( "button#profile-edit-button" ).show();
      $("div#new-photo-upload").hide();
      $("div#hide-password").hide();
      });
    });
  <% else %>
    $(document).ready( function() {
      $(".form-edit").prop('disabled', true);
    });
  <% end %>


  <% end %>
<% end %>

app/views/shared/navbar_offline.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand navbar-wagon-link">
    <h3>ShedShare <i class="fa fa-handshake-o" aria-hidden="true"></i></h3>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Log in Link -->
    <%= link_to "Log In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Button (call-to-action) -->
    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Log In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>